### ISSUE TITLE
Purpose of `f_nom` in ALPACA

### ISSUE THREAD

**Issue by bkj** [StanfordASL/ALPaCA#1]
Are you able to explain the purpose of [f_nom in ALPACA](https://github.com/StanfordASL/ALPaCA/blob/8a1f233cc662678c81aec4bffea135d929016020/main/alpaca.py#L9)?  Is this modification referenced in the paper at all?

Thanks

**Comment by apoorva-sharma** [comment]
Hey Ben,

The purpose of f_nom is to provide a nominal transformation from x to y, and have the model only learn and adapt the error model online. Mathematically, the model is changed to be:

`y = K^T \phi(x) + f_nom(x)`

We did not use this for any of the simple function regression experiments in the paper.

For the dynamical systems modeling experiments, we use the ALPaCA framework to model the change in state. This is accomplished by using the model:

`x[t+1] = K^T \phi(x[t], u[t]) + f_nom(x[t],u[t])`

and setting 

`f_nom(x[t],u[t]) = x[t]`

In the code, this is the default behavior when using the AdaptiveDynamics class without specifying f_nom manually.

Hope that clarifies things!

Cheers,
Apoorva
